Developmemt
sergalkin/gophermart-diplom pull request #1
Opened 2022-06-09 23:23 UTC by sergalkin

2022-06-10 16:15 UTC, lugingf requested changes
В общем весь проект написан хорошо, читается и понимается легко. Только одно пожелание, но считаю, что оно довольно критичное. Давай поправим

2022-06-10 16:15 UTC, lugingf commented on internal/gophermart/handlers/orders.go
> +		go o.accrual(login, order)
А что если у нас будет 1000 запросов в секунду, а accrual упадет? У нас будут порождаться горутины, а обновлений запросов не будет?

Я бы предложил отвязать процесс обновления статуса заказов от HTTP, пусть это будет отдельный процесс, который запускается из main()

2022-06-10 16:43 UTC, sergalkin commented on internal/gophermart/handlers/orders.go
> +		go o.accrual(login, order)
Согласен, грамотное замечание.

Есть вот такая идея:
1) `POST /api/user/orders` - убираем вызов горутины, добавляем запись в канал
2) Выносим создание горутины(воркер пула) в main
3) Внутри этого воркер пула(горутины) в бесконечном цикле берем данные из канала и вызываем этот `o.accrual`(ну только вынесу его в отдельный хендлер мб)

Так вроде должно быть нормально, да?

2022-06-10 16:45 UTC, lugingf commented on internal/gophermart/handlers/orders.go
> +		go o.accrual(login, order)
Идея огонь! Давай так и сделаем!

2022-06-24 13:19 UTC, lugingf approved these changes
Принято :)

2022-06-24 13:22 UTC, merged